### ISSUE TITLE
ModUI not working in 0.3.4 and Townscaper not working in 0.5.7

### ISSUE THREAD

**Issue by ND-64** [DigitalzombieTLD/TownscaperModUI#1]
you have to install MelonLoader in version 0.4.3 otherwise the game wont boot, however ModUI only works in if MelonLoader is installed on version 0.5.7
ive tried launching the game when MelonLoader is installed on 0.5.7 but it would just pop up the MeloanLoader window and fail to launch, meanwhile when i have MelonLaoder installed on version 0.4.3 ModUI will get an error saying "ModUI.DZColorSlider has unsupported parameter Single value of type System.Single"

**Comment by DigitalzombieTLD** [comment]
you can ignore the "unsupported paramenter message.

as for 0.5.7:
- Uninstall MelonLoader (with the installer)
- Create a new shortcut to your Townscaper.exe
- Add   --melonloader.disablestartscreen as a startargument to the shortcut
- Install MelonLoader 0.5.7
- Start the game through the new shortcut from now on
